### ISSUE TITLE
Newest traverse update from the 31st making server crash when booting

### ISSUE THREAD

**Issue by zachsai** [MysticMods/Traverse#33]
### General Information

**Describe the bug:**

[31.12 19:52:36] [Server] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/entity/BlazeRenderer (java.lang.ClassNotFoundException: null)
[31.12 19:52:36] [Server] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.entity.BlazeRenderer was not found outvoted.mixins.json:MixinBlazeRenderer
[31.12 19:52:36] [Server] [PlaceboASM]Patching LootTableManager#apply
[31.12 19:52:38] [Server] [Serene Seasons Transformer]Transforming func_201854_a in net/minecraft/world/biome/Biome
[31.12 19:52:38] [Server] [Serene Seasons Transformer]Patched 1 calls
[31.12 19:52:38] [Server] [Serene Seasons Transformer]Transforming func_201850_b in net/minecraft/world/biome/Biome
[31.12 19:52:38] [Server] [Serene Seasons Transformer]Patched 1 calls
[31.12 19:52:38] [Server] Exception in thread "main" [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 7 more
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$0(WorldGenRegistries.java:33)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$6(WorldGenRegistries.java:89)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.server.Main.main(Main.java:92)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	... 13 more
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.throwables.MixinError: Encountered undecorated Accessor method in traverse.mixins.json:AccessorSetFireInfo applying to net.minecraft.block.FireBlock
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.isAlreadyMerged(MixinApplicatorStandard.java:632)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:548)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1054)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[31.12 19:52:38] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	... 32 more
**To Reproduce:**

1. First Step
2. First Step
3. First Step

**Expected behavior:**

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 
- Ecc...

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 35.1.13
- Minecraft: 1.16.4
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
That's an odd one. Let me look into it.

**Comment by noobanidus** [comment]
Are you able to upload the full log file?

**Comment by noobanidus** [comment]
I'm not really sure why this is happening. I'll revert to using an access transformer on the method instead. I'm not able to replicate it in my environment, either in single-player/integrated server or with a dedicated server. It's possible I've done the accessor wrong, but from the documentation I've been able to find it is correct.
