### ISSUE TITLE
Crash caused potentially by Traverse

### ISSUE THREAD

**Issue by ghost** [MysticMods/Traverse#38]
### General Information

**Describe the bug:**
Doing more testing, but an area of the world in my server seems to cause a crash and kills a bunch of threads until server hangs causing shutdown.

**To Reproduce:**
1. I start server, load into world, go to specific area (will test if occurrs in other areas)
2. World stops responding to changes (i.e. a server hang, no tick processing)
3. Threads start falling and dying in the server until world hangs and dies

### Environment Versions
traverse-1.16.4-0.4.3.8 for forge

**Other Versions:**
- Conflicting mod (if regarding mod integration): 
- Other mods you think could cause issues:Potentially conflicting, Terraforged, Performant
- Forge: 35.1.37
- Minecraft: 1.16.4
***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**
Debug: https://gist.github.com/TechniumUnlimited/a7e1ef6b369a0b47bf143ef1928bfa8f
**Crash Report (if available):**

https://pastebin.com/NkAA5PKY

***

**Additional context (optional):**
quite an ambiguous bug.. so I apologize if it turns out to be clearly not of traverse's fault

It mentions traverse several times before the thread errors that mention terraforged, performant, bees, etc, so hard to tell if it is in fact a bug of traverse
```[17Jan2021 21:07:57.974] [Worker-Main-39/DEBUG] [FeatureManager/]: Unable to determine issues. See stacktrace:
java.lang.NullPointerException: null
	at java.util.function.Function.lambda$andThen$1(Unknown Source) ~[?:1.8.0_261]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$getCodec$10(KeyDispatchCodec.java:123) ~[?:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.getCodec(KeyDispatchCodec.java:123) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$new$0(KeyDispatchCodec.java:46) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:79) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?]
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$8.encode(RecordCodecBuilder.java:379) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$9.encode(RecordCodecBuilder.java:443) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$4.encode(RecordCodecBuilder.java:224) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$6.encode(RecordCodecBuilder.java:298) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?]
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.MapEncoder$1.encode(MapEncoder.java:26) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:92) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?]
	at net.minecraft.util.registry.RegistryKeyCodec.encode(SourceFile:44) ~[?:?]
	at net.minecraft.util.registry.RegistryKeyCodec.encode(SourceFile:13) ~[?:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?]
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$4.encode(RecordCodecBuilder.java:222) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?]
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.MapEncoder$1.encode(MapEncoder.java:26) ~[?:?]
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:92) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?]
	at com.terraforged.mod.featuremanager.util.codec.Codecs.encode(Codecs.java:86) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.featuremanager.util.codec.Codecs.encode(Codecs.java:96) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.featuremanager.FeatureSerializer.serialize(FeatureSerializer.java:44) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.featuremanager.modifier.FeatureModifiers.getFeature(FeatureModifiers.java:103) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.featuremanager.FeatureManager.compute(FeatureManager.java:122) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.featuremanager.FeatureManager.create(FeatureManager.java:98) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.SetupFactory.createFeatureManager(SetupFactory.java:138) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.GeneratorResources.<init>(GeneratorResources.java:62) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.GeneratorResources.lambda$factory$0(GeneratorResources.java:74) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.engine.concurrent.task.LazySupplier.lambda$factory$0(LazySupplier.java:52) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.engine.concurrent.task.LazySupplier.create(LazySupplier.java:40) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.engine.concurrent.task.LazyCallable.call(LazyCallable.java:68) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.engine.concurrent.task.LazyCallable.get(LazyCallable.java:107) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.TFChunkGenerator.queueChunk(TFChunkGenerator.java:338) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.TFChunkGenerator.queueChunk(TFChunkGenerator.java:334) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.generator.StructureGenerator.generateStructureStarts(StructureGenerator.java:61) ~[terraforged:1.16.4-0.2.0-RC-2]
	at com.terraforged.mod.chunk.TFChunkGenerator.func_242707_a(TFChunkGenerator.java:184) ~[terraforged:1.16.4-0.2.0-RC-2]
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$2(ChunkStatus.java:41) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:522) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) [?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) [?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) [?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]

**Comment by ghost** [comment]
I also reference this issue in Terraforged's github here: https://github.com/TerraForged/tracker/issues/15

**Comment by ghost** [comment]
After further inspection of the debug log, it seems it also references problems serializing even vanilla minecraft biomes - so it seems less likely to me that it is a specific biome mod's fault, and more likely it is performant or terraforged, I will close this for now unless terraforged or performant see reason that it is this mod's fault.

**Comment by noobanidus** [comment]
I've replied on the Terraforged side. I recommend trying out Blame to see if you can track down the cause that way.

**Comment by TechniumUnlimited** [comment]
I do infact have blame and unfortunately at least afai saw, no blame reports were generated related to the issue at the time of the issue
